# Update the config
---
name: update_config
description: Update server config
runner_type: python-script
entry_point: update_config.py
enabled: true
parameters:
  server_id:
    type: string
    required: true
  key_name:
    type: string
    default: mock-cloud-provider-serverdata
  action:
    type: string
    default: upsert
  server_state:
    type: string
    default: running